// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArmController.REST
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;

    /// <summary>
    /// TestTarget operations.
    /// </summary>
    public partial interface ITestTarget
    {
        /// <param name='id'>
        /// </param>
        /// <param name='timeStamp'>
        /// </param>
        /// <param name='x'>
        /// </param>
        /// <param name='y'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> ReportTouchWithHttpMessagesAsync(long id, string timeStamp, double x, double y, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
