// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ArmController.REST
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;

    /// <summary>
    /// Extension methods for TestTarget.
    /// </summary>
    public static partial class TestTargetExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='timeStamp'>
            /// </param>
            /// <param name='x'>
            /// </param>
            /// <param name='y'>
            /// </param>
            public static string ReportTouch(this ITestTarget operations, long id, string timeStamp, double x, double y)
            {
                return Task.Factory.StartNew(s => ((ITestTarget)s).ReportTouchAsync(id, timeStamp, x, y), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='timeStamp'>
            /// </param>
            /// <param name='x'>
            /// </param>
            /// <param name='y'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> ReportTouchAsync(this ITestTarget operations, long id, string timeStamp, double x, double y, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ReportTouchWithHttpMessagesAsync(id, timeStamp, x, y, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
